'use strict';
// Dependency-free LAN server: serves the game and relays room messages.
const http=require('node:http');const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const child=require('node:child_process');
const PORT=Number(process.env.PORT)||8080;const HTML=path.join(__dirname,'index.html');const rooms=new Map();
const send=(client,message)=>{if(client.closed)return;const data=Buffer.from(JSON.stringify(message));if(data.length>1024*1024)return;let head;if(data.length<126){head=Buffer.from([0x81,data.length])}else if(data.length<65536){head=Buffer.alloc(4);head[0]=0x81;head[1]=126;head.writeUInt16BE(data.length,2)}else{head=Buffer.alloc(10);head[0]=0x81;head[1]=127;head.writeBigUInt64BE(BigInt(data.length),2)}client.socket.write(Buffer.concat([head,data]))};
function close(client){if(client.closed)return;client.closed=true;let room=rooms.get(client.room);if(!room)return;if(room.host===client){if(room.guest){send(room.guest,{type:'peer',connected:false});room.guest.socket.end()}rooms.delete(client.room)}else if(room.guest===client){room.guest=null;send(room.host,{type:'peer',connected:false})}}
function route(client,m){if(typeof m!=='object'||m===null||typeof m.type!=='string')return;if(m.type==='create'){if(client.room)return;let code;do{code=crypto.randomBytes(4).toString('hex').slice(0,5).toUpperCase()}while(rooms.has(code));rooms.set(code,{host:client,guest:null,active:false});client.room=code;client.role='host';send(client,{type:'room',role:'host',code});return}if(m.type==='join'){if(client.room)return;let code=String(m.code||'').toUpperCase(),room=rooms.get(code);if(!room||room.guest||room.active){send(client,{type:'error',message:'Room unavailable, full, or currently in a raid.'});return}room.guest=client;client.room=code;client.role='guest';send(client,{type:'room',role:'guest',code});send(room.host,{type:'peer',connected:true,kit:m.kit,upgrades:m.upgrades});return}let room=rooms.get(client.room);if(!room)return;if(client.role==='host'&&['start','state','end','sound'].includes(m.type)){if(m.type==='start')room.active=true;if(m.type==='end')room.active=false;if(room.guest)send(room.guest,m);return}if(client.role==='guest'&&['input','action','kit'].includes(m.type)){send(room.host,m)}}
function incoming(client,chunk){client.buffer=Buffer.concat([client.buffer,chunk]);while(client.buffer.length>=2){let b=client.buffer,opcode=b[0]&15,masked=!!(b[1]&128),len=b[1]&127,off=2;if(!masked){client.socket.destroy();return}if(len===126){if(b.length<4)return;len=b.readUInt16BE(2);off=4}else if(len===127){if(b.length<10)return;let big=b.readBigUInt64BE(2);if(big>BigInt(1024*1024)){client.socket.destroy();return}len=Number(big);off=10}if(len>1024*1024){client.socket.destroy();return}if(b.length<off+4+len)return;let mask=b.subarray(off,off+4),msg=Buffer.from(b.subarray(off+4,off+4+len));client.buffer=b.subarray(off+4+len);for(let i=0;i<msg.length;i++)msg[i]^=mask[i&3];if(opcode===8){client.socket.end();return}if(opcode===9){client.socket.write(Buffer.from([0x8a,0x00]));continue}if(opcode!==1)continue;try{route(client,JSON.parse(msg.toString('utf8')))}catch{}}}
const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/api/addresses'){let urls=[],vpnUrls=[],interfaces={};try{interfaces=os.networkInterfaces()}catch{}for(let items of Object.values(interfaces))for(let iface of items||[])if(iface.family==='IPv4'&&!iface.internal){let url='http://'+iface.address+':'+PORT;urls.push(url);let parts=iface.address.split('.').map(Number);if(parts[0]===100&&parts[1]>=64&&parts[1]<=127)vpnUrls.push(url)}urls.sort((a,b)=>Number(!/http:\/\/192\.168\./.test(a))-Number(!/http:\/\/192\.168\./.test(b)));res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({urls,vpnUrls}));return}if(pathname!=='/'&&pathname!=='/index.html'){res.writeHead(404);res.end('Not found');return}fs.readFile(HTML,(err,data)=>{if(err){res.writeHead(500);res.end('Game file unavailable');return}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self' 'unsafe-inline' ws: wss: data:"});res.end(data)})});
server.on('upgrade',(req,socket)=>{if(req.url!=='/'||req.headers.upgrade?.toLowerCase()!=='websocket'||!req.headers['sec-websocket-key']){socket.destroy();return}let accept=crypto.createHash('sha1').update(req.headers['sec-websocket-key']+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');let client={socket,buffer:Buffer.alloc(0),room:null,role:null,closed:false};socket.on('data',d=>incoming(client,d));socket.on('close',()=>close(client));socket.on('error',()=>close(client))});
server.listen(PORT,'0.0.0.0',()=>{console.log(`BLACKSITE co-op ready at http://localhost:${PORT}\nClick CREATE ROOM, then COPY LINK. Use START_ONLINE.cmd for friends outside your network.\nPress Ctrl+C to stop.`);if(process.platform==='win32')child.exec(`start "" "http://localhost:${PORT}"`,{windowsHide:true})});
